meta_name: "Good Luck Poker"
meta_title: "Good Luck Poker - Trust your skill, not your luck"
meta_description: "Play poker with you luck ratio in mind, you can't blame the cards anymore!"
meta_image: "good-luck-image.jpg" # should exist in `app/assets/images/`
twitter_account: "@Ninjao10"   # required for Twitter Cards
